import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/Shared/Navbar";
import { Footer } from "@/components/Shared/Footer";
import TopLoader from 'nextjs-toploader'
import AppProvider from "./provider/AppProvider";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Next Level",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#131313]`}
      >
        <AppProvider>
          <Navbar />
          <TopLoader
            color="#2563eb"
            easing="ease-in"
            showSpinner={false}
          />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
