import type { Metadata } from "next";
import { Manrope, Racing_Sans_One } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Shared/Navbar";
import { Footer } from "@/components/Shared/Footer";
import TopLoader from 'nextjs-toploader'
import AppProvider from "./provider/AppProvider";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const racingSansOne = Racing_Sans_One({
  subsets: ["latin"],
  variable: "--font-heading",
  weight: "400", 
});


export const metadata: Metadata = {
  title: "Next Level",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.variable} ${racingSansOne.variable} antialiased bg-[#131313]`}
      >
        <AppProvider>
          <Navbar />
          <TopLoader
            color="#2563eb"
            easing="ease-in"
            showSpinner={false}
          />
          {children}
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
